// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SearchbynameTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void productsearchbyname() {
    // Test name: Product-search-by-name
    // Step # | name | target | value | comment
    // 1 | open | https://skrylexx.github.io/Products_CRUDS/ |  | 
    driver.get("https://skrylexx.github.io/Products_CRUDS/");
    // 2 | setWindowSize | 974x1032 |  | 
    driver.manage().window().setSize(new Dimension(974, 1032));
    // 3 | click | id=inputSearch |  | 
    driver.findElement(By.id("inputSearch")).click();
    // 4 | type | id=inputSearch | Be | 
    driver.findElement(By.id("inputSearch")).sendKeys("Be");
    // 5 | sendKeys | id=inputSearch | ${KEY_ENTER} | 
    driver.findElement(By.id("inputSearch")).sendKeys(Keys.ENTER);
    // 6 | click | css=body |  | 
    driver.findElement(By.cssSelector("body")).click();
    // 7 | assertElementPresent | css=tr:nth-child(1) > td:nth-child(2) |  | 
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("tr:nth-child(1) > td:nth-child(2)"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void productsearchbynamenothingfound() {
    // Test name: Product-search-by-name-nothing-found
    // Step # | name | target | value | comment
    // 1 | open | https://skrylexx.github.io/Products_CRUDS/ |  | 
    driver.get("https://skrylexx.github.io/Products_CRUDS/");
    // 2 | setWindowSize | 974x1032 |  | 
    driver.manage().window().setSize(new Dimension(974, 1032));
    // 3 | click | id=inputSearch |  | 
    driver.findElement(By.id("inputSearch")).click();
    // 4 | type | id=inputSearch | Test | 
    driver.findElement(By.id("inputSearch")).sendKeys("Test");
    // 5 | sendKeys | id=inputSearch | ${KEY_ENTER} | 
    driver.findElement(By.id("inputSearch")).sendKeys(Keys.ENTER);
    // 6 | assertElementPresent | css=.container |  | 
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".container"));
      assert(elements.size() > 0);
    }
  }
}
