// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ProductnamewithoutmajTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void productnamewithoutmaj() {
    // Test name: Product name without maj
    // Step # | name | target | value | comment
    // 1 | open | /Products_CRUDS/ |  | 
    driver.get("https://skrylexx.github.io/Products_CRUDS//Products_CRUDS/");
    // 2 | click | id=inputName |  | 
    driver.findElement(By.id("inputName")).click();
    // 3 | type | id=inputName | aaa | 
    driver.findElement(By.id("inputName")).sendKeys("aaa");
    // 4 | type | id=inputPrice | 850 | 
    driver.findElement(By.id("inputPrice")).sendKeys("850");
    // 5 | select | id=inputCategory | label=MOBILE | 
    {
      WebElement dropdown = driver.findElement(By.id("inputCategory"));
      dropdown.findElement(By.xpath("//option[. = 'MOBILE']")).click();
    }
    // 6 | select | id=inputCategory | label=TV | 
    {
      WebElement dropdown = driver.findElement(By.id("inputCategory"));
      dropdown.findElement(By.xpath("//option[. = 'TV']")).click();
    }
    // 7 | click | id=inputName |  | 
    driver.findElement(By.id("inputName")).click();
    // 8 | assertElementPresent | id=alertName |  | 
    {
      List<WebElement> elements = driver.findElements(By.id("alertName"));
      assert(elements.size() > 0);
    }
  }
}
